
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Nov 22 18:10:49 CET 2013
//----------------------------------------------------

package pl.edu.pjwstk.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSymbols {
  /* terminals */
  public static final int GROUP_AS = 45;
  public static final int FORALL = 41;
  public static final int DIVIDE = 13;
  public static final int STRING_LITERAL = 8;
  public static final int RIGHT_BOX_BRACKET = 55;
  public static final int MORE_OR_EQUAL = 27;
  public static final int CHAR_LITERAL = 9;
  public static final int EQUALS = 15;
  public static final int USING = 63;
  public static final int XOR = 24;
  public static final int GROUPBY_DESC = 7;
  public static final int MINUS_FUNCTION = 48;
  public static final int FORANY = 42;
  public static final int LESS = 25;
  public static final int MINUS = 11;
  public static final int WHERE = 34;
  public static final int INSTANCEOF = 62;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int SEMICOLON = 56;
  public static final int NOT = 46;
  public static final int AND = 23;
  public static final int RANGE = 59;
  public static final int CLOSE_BY = 40;
  public static final int LESS_OR_EQUAL = 28;
  public static final int IN = 32;
  public static final int OR = 22;
  public static final int BAG = 36;
  public static final int QUESTION_MARK = 60;
  public static final int PLUS = 10;
  public static final int MULTIPLY = 12;
  public static final int LEFT_CURLY_BRACKET = 52;
  public static final int MIN = 29;
  public static final int DOT = 33;
  public static final int LEFT_ROUND_BRACKET = 50;
  public static final int EOF = 0;
  public static final int NEW = 58;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int MODULO = 14;
  public static final int EXISTS = 47;
  public static final int JOIN = 43;
  public static final int LEFT_BOX_BRACKET = 54;
  public static final int UNIQUE = 17;
  public static final int AVG = 20;
  public static final int COLON = 61;
  public static final int FOREACH = 57;
  public static final int UNION = 18;
  public static final int ORDER_BY = 39;
  public static final int NOT_EQUALS = 16;
  public static final int SUM = 19;
  public static final int SEQUENCE = 37;
  public static final int DOUBLE_LITERAL = 3;
  public static final int INTERSECT = 49;
  public static final int AS = 44;
  public static final int COUNT = 21;
  public static final int STRUCT = 38;
  public static final int GROUPBY_ASC = 6;
  public static final int RIGHT_CURLY_BRACKET = 53;
  public static final int MAX = 30;
  public static final int DEREF = 35;
  public static final int MORE = 26;
  public static final int RIGHT_ROUND_BRACKET = 51;
  public static final int INTEGER_LITERAL = 2;
  public static final int IDENTIFIER = 5;
}

